project:
  type: website

website:
  title: "spatialists.ch – geospatial news"
  site-url: https://spatialists.ch
  description: "A blog about geospatial topics"
      
format:
  html:
    theme: superhero
    css: styles.css
