project:
  type: website

website:
  title: "spatialists.ch – geospatial news"
  site-url: https://spatialists.ch
  description: "A blog about geospatial topics"
  favicon: assets/favicon.png
  image: assets/titlecard.jpg
  navbar:
    right: 
      - text: About
        href: about.qmd
      - text: Feed
        href: index.xml

  search:
    location: navbar
    type: overlay

format:
  html:
    theme: superhero
    css: styles.css
