name: Render and publish (spatialists.ch)

on:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        
      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render
        uses: quarto-dev/quarto-actions/render@v2 

      - name: Push contents of _site folder to repo
        uses: github-actions-x/commit@v2.9
        with:
          push-branch: 'main'
          commit-message: 'Render website'
          force-add: 'true'
          files: _site/ 
          name: autoupdate

      - name: Copy quarto rendered static files to FTP Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASSWORD }}
          # FTP_DIR is defined relatively to the user's "root" directory.
          # FTP_DIR must be a folder (must end with /)
          server-dir: .
          local-dir: ./_site/
          protocol: ftps
          log-level: verbose
          exclude: |
          dry-run: false
